server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
spring:
  redis:
    url: ${REDIS_URL:}
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
          handshake-timeout: 10000
      filter:
        request-rate-limiter:
          deny-empty-key: false
          empty-key-status-code: 503
      routes:
        - id: alpha-sound-service
          uri: lb://alpha-sound-service/alpha-sound
          predicates:
            - Path=/alpha-sound/**
        - id: kappa-talk-server
          uri: lb://kappa-talk-server/kappa-talk
          predicates:
            - Path=/kappa-talk/**
        - id: lambda-auth-service
          uri: lb://lambda-auth-service/lambda-auth
          predicates:
            - Path=/lambda-auth/**
          filters:
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@addressKeyResolver}"
              redis-rate-limiter.replenishRate: 100
              redis-rate-limiter.burstCapacity: 50
              redis-rate-limiter.requestedTokens: 1
        - id: delta-notification-service
          uri: lb://delta-notification-service/delta-notification
          predicates:
            - Path=/delta-notification/**
        - id: omega-buy-service
          uri: lb://omega-buy-service/omega-buy
          predicates:
            - Path=/omega-buy/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false
logging:
  config: classpath:log4j-spring.xml
  level:
    org.springframework.cloud.gateway: TRACE
    com.vengeance.gamma: DEBUG