server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
spring:
  redis:
    url: ${REDIS_URL:}
logging:
  config: classpath:log4j-spring.xml
  level:
    org.springframework.cloud.gateway: TRACE
    com.vengeance.gamma: DEBUG