logging:
  config: classpath:log4j-spring.xml
  level:
    org.springframework.cloud.gateway: DEBUG
    root: INFO
server:
  port: 8020
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: gamma-gateway-service
  redis:
    host: ${REDIS_HOST:}
    port: ${REDIS_PORT:}
    database: ${REDIS_DB:}
    password: ${REDIS_PASSWORD:}