logging:
  config: classpath:log4j-spring.xml
  level:
    org.springframework.cloud.gateway: INFO
    root: INFO
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
spring:
  application:
    name: gamma-gateway-service
  redis:
    host: ${REDIS_HOST:}
    port: ${REDIS_PORT:}
    database: ${REDIS_DB:}
    password: ${REDIS_PASSWORD:}
